### ISSUE TITLE
gulp-plugins not always working v0.6.0

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#662]
Hello,

I'm working through my build, and am wanting most of it in Assemble as opposed to in gulp. However, in some cases (latest gulp-sitemap), there seems to be some difference between how assemble and gulp handle things.

As an example, gulp-sitemap:

```
gulp.task('sitemap', function () {
    gulp.src('dist/**/*.html')
        .pipe(sitemap({
                siteUrl: 'http://smaty.se'
        })) // Returns sitemap.xml
        .pipe(gulp.dest('dist'));
});
```
This works, no problems. Moving it over to Assemblefile.js:

```
assemble.task('sitemap', function () {
    assemble.src('dist/**/*.html')
        .pipe(sitemap({
                siteUrl: 'http://smaty.se'
        })) // Returns sitemap.xml
        .pipe(assemble.dest('dist'));
});
```

This throws the following error

````
/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/gulp-util/lib/PluginError.js:102
    return '    ' + prop + ': ' + self[prop];
                                ^
TypeError: Cannot convert object to primitive value
    at stringifyProperty (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/gulp-util/lib/PluginError.js:102:33)
    at Array.map (native)
    at PluginError._messageDetails (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/gulp-util/lib/PluginError.js:101:27)
    at PluginError._messageWithDetails (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/gulp-util/lib/PluginError.js:80:22)
    at PluginError.toString (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/gulp-util/lib/PluginError.js:124:16)
    at Stream.<anonymous> (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/context.js:78:13)
    at Stream.emit (events.js:104:17)
    at Stream.emitted [as emit] (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
    at DestroyableTransform.handleEnd (/Users/mariehogebrandt/Documents/vendela/smaty_se/node_modules/assemble/node_modules/event-stream/node_modules/duplexer/index.js:81:21)
    at DestroyableTransform.emit (events.js:129:20)
```

Now, since I can get it to work using gulp I can keep it as a gulp task, no problems, but I figured I'd draw your attention to it. I've only tried this on a MacBook.

**Comment by jonschlinkert** [comment]
hmm, there shouldn't be. any gulp plugin should work, I'll mark as a bug and look into it

**Comment by Melindrea** [comment]
I have a bit more info about what's going on on this particular bit. I have no clue if it means anything to you, but this is three test cases. Each of them load the files and pipe them through `gulp-sitemap`, or rather, a modified one that logs `file` and then `file.stat`.

```
// Right after assembl.src()
<File "stories/nanowrimo.md" <Buffer 0a 0a 59 6f 75 20 64 6f 6e 27 74 20 6b 6e 6f 77 20 77 68 61 74 20 74 68 61 74 20 69 73 3f 20 57 65 6c 6c 2c 20 6e 6f 20 77 6f 72 72 69 65 73 2c 20 49 ... >>

file.stat:
null

// After saving it to dest
<File "stories/nanowrimo.md" <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 21 2d 2d 5b 69 66 20 6c 74 20 49 45 20 39 5d 3e 20 20 20 20 20 20 20 20 20 3c 68 74 6d 6c 20 63 6c ... >>

file.stat:
{ dev: undefined,
  mode: null,
  nlink: undefined,
  uid: undefined,
  gid: undefined,
  rdev: undefined,
  blksize: undefined,
  ino: undefined,
  size: undefined,
  blocks: undefined,
  atime: Invalid Date,
  mtime: Invalid Date,
  ctime: Invalid Date,
  birthtime: Invalid Date }

// Loading via gulp
<File "stories/nanowrimo/index.html" <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 21 2d 2d 5b 69 66 20 6c 74 20 49 45 20 39 5d 3e 20 20 20 20 20 20 20 20 20 3c 68 74 6d 6c 20 63 6c ... >>

file.stat:
{ dev: 64512,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 22676981,
  size: 7809,
  blocks: 16,
  atime: Wed Mar 25 2015 15:30:00 GMT+0100 (CET),
  mtime: Wed Mar 25 2015 15:30:00 GMT+0100 (CET),
  ctime: Wed Mar 25 2015 15:30:00 GMT+0100 (CET),
  birthtime: Wed Mar 25 2015 15:30:00 GMT+0100 (CET) }
```

So, there seems to be somewhere that it's not playing nicely with `file.stat`?

**Comment by doowb** [comment]
Thanks @Melindrea this helps a lot because I think I know where this is happening and can work on a fix now.

**Comment by jonschlinkert** [comment]
yes, that definitely helps a lot!

**Comment by Melindrea** [comment]
Awesome =) I realised yesterday that my current building of the sitemap is ... kind of faulty (it uses stat of the file, and since that's the file that I *just* built via assemble, the last modified is incorrect). I'll still probably end up needing to fork it for my needs, but that's life =)

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble and has been resolved
