### ISSUE TITLE
TypeError: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by lmmurphy** [assemble/assemble#673]
I just installed assemble@beta today.

I have the following assemblefile.js -

```javascript
var assemble = require('assemble');
var less = require('gulp-less');

assemble.task('test1', function () {
	assemble.copy('temp/index.hbs', 'dist');
});

assemble.task('test2', function () {
	assemble.src('temp/*.hbs')
	    .pipe(assemble.dest('dist/'));
});

assemble.task('css', function () {
  assemble.src('src/less/*.less')
    .pipe(less())
    .pipe(assemble.dest('dist/assets/css'));
});
```

I was getting the 'TypeError: Cannot call method 'on' of undefined' error using assemble.src while running my css task so I decided to modify the assemblefile.js to see if I could get something working thinking my installation might have gone wonky.   I added the test1 target which does an assemble.copy and success... it worked!  So then I added the test2 target which does an assemble.src and got the 'TypeError: Cannot call method 'on' of undefined' again.

The command line output is -

```javascript
/Users/xxx/Code/test $ ls -l dist
/Users/xxx/Code/test $ assemble test1
[18:46:42] Using assemblefile ~/Code/test/assemblefile.js
[18:46:42] Starting 'test1'...
[18:46:42] Finished 'test1' after 5.3 ms
/Users/xxx/Code/test $ ls -l dist
total 8
-rw-r--r--  1 xxx  staff  101 Mar 22 18:46 index.hbs
/Users/xxx/Code/test $ assemble test2
[18:46:54] Using assemblefile ~/Code/test/assemblefile.js
[18:46:54] Starting 'test2'...
[18:46:54] 'test2' errored after 6.33 ms
[18:46:54] TypeError: Cannot call method 'on' of undefined
    at proxyStream (/Users/xxx/Code/test/node_modules/assemble/node_modules/event-stream/node_modules/duplexer/index.js:65:16)
    at Array.forEach (native)
    at forEach (/Users/xxx/Code/test/node_modules/assemble/node_modules/event-stream/node_modules/duplexer/index.js:11:20)
    at duplex (/Users/xxx/Code/test/node_modules/assemble/node_modules/event-stream/node_modules/duplexer/index.js:27:5)
    at Object.module.exports (/Users/xxx/Code/test/node_modules/assemble/node_modules/event-stream/node_modules/stream-combiner/index.js:8:17)
    at createStack (/Users/xxx/Code/test/node_modules/assemble/lib/stack.js:53:21)
    at Assemble.exports.src (/Users/xxx/Code/test/node_modules/assemble/lib/stack.js:72:10)
    at Assemble.src (/Users/xxx/Code/test/node_modules/assemble/lib/index.js:185:15)
    at Assemble.<anonymous> (/Users/xxx/Code/test/assemblefile.js:9:11)
    at module.exports (/Users/xxx/Code/test/node_modules/assemble/node_modules/orchestrator/lib/runTask.js:34:7)
/Users/xxx/Code/test $
```

Do I have something misconfigured?  Some sort of options that I need set up?

Thanks in advance.

BTW - the README.md contains the following code example -

```javascript
assemble.task('css', function () {
  assemble.src('styles/*.less')
    .pipe(less());
    .pipe(assemble.dest('dist/assets/css'));
});
```
The semi-colon at the end of the .pipe(less()); line looks like it needs to be removed.

**Comment by doowb** [comment]
There was a change in a dependency that didn't get updated in assemble. Try to reinstall assemble with `npm i assemble@beta` to get the latest beta and see if that works.

**Comment by lmmurphy** [comment]
Thanks!  No more error upon reinstall.
