### ISSUE TITLE
assemble.data fails when cwd contains dots (.)

### ISSUE THREAD

**Issue by fterrier** [assemble/assemble#691]
We had an issue with assemble.data that caused this error to occur :
```
SyntaxError: Unexpected token o
    at Object.parse (native)
    at readData (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:235:19)
    at read (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:215:10)
    at Plasma.mergeFile (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:140:13)
    at Plasma.glob (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:174:29)
    at Plasma.mergeArray (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:115:18)
    at Plasma.load (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:82:17)
    at Assemble.Cache.plasma (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/index.js:515:28)
    at Assemble.Cache.data (/Users/username/my.super.project/node_modules/assemble/node_modules/template/node_modules/config-cache/index.js:566:25)
    at Object.<anonymous> (/Users/username/my.super.project/gulptasks/assemble.js:16:10)
```

We tracked down the problem and noticed it is because of our working directory name containing several dots.

To reproduce:
1. create a project folder with several dots in the name
2. create a `data` folder in it that contains json files
3. create a gulptask that uses assemble, for example:
```
var gulp = require('gulp');
var assemble = require('assemble');
var gulpAssemble = require('gulp-assemble');

assemble.data(['/data/*.json']);
gulp.task('assemble-single-components', function() {
    return gulp.src([**/*.hbs'])
    .pipe(gulpAssemble(assemble))
    .pipe(gulp.dest(config.paths.dev));
});
```

We tracked down the issue already to this line in the plasma dependency in file `index.js` on line 137:
```
fp = relative(path.resolve(opts.cwd, fp));
```

This causes the `fp` variable to also contains the project name, which is then wrong, relative to the project directory.

I created an issue on https://github.com/jonschlinkert/relative project:
https://github.com/jonschlinkert/relative/issues/5

**Comment by jonschlinkert** [comment]
closing since this was resolved on the `relative` lib
