### ISSUE TITLE
Loading "assemble.js" tasks...ERROR >> Error: Cannot find module 'grunt'

### ISSUE THREAD

**Issue by foxx** [assemble/assemble#700]
Possibly related to a similar issue seen [here][1]. Seems that deps are not being resolved correctly, any ideas? Possibly a problem with resolve-dep?

```
$ grunt -d -v --stack
Loading "assemble.js" tasks...ERROR
>> Error: Cannot find module 'grunt'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/tmp/tmp.I0luo8CrFI/grunt-assemble/lib/utils.js:10:13)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
```

Here are my versions;

```
npm=2.7.4
nvm=0.25.0
node=v0.12.2
grunt-assemble 0.2.0
grunt-cli v0.1.13
grunt v0.4.5
```

[1]: https://github.com/jmreidy/grunt-browserify/issues/325

**Comment by foxx** [comment]
Sorry, raised in the wrong place

**Comment by foxx** [comment]
Raised here;
https://github.com/assemble/grunt-assemble/issues/13
