### ISSUE TITLE
having trouble loading yaml and json data with 0.6.0-beta5

### ISSUE THREAD

**Issue by hyzhak** [assemble/assemble#723]
I have tried to load yaml and json data but it doesn't work.

For yaml I this part:

```javascript
assemble.data('projects/list.yaml');
console.log(
	JSON.stringify(assemble.get('data'))
);
```

 logs:

```
{"list":["object Object"]}
```

for json I got error:

```
[02:32:28] SyntaxError: Unexpected token o
    at Object.parse (native)
    at readData (some_project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:233:19)
    at read (some_project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:214:10)
    at Plasma.mergeFile (some_project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:139:13)
    at Plasma.load (some_project/node_modules/assemble/node_modules/template/node_modules/config-cache/node_modules/plasma/index.js:76:19)
    at Assemble.Cache.plasma (some_project/node_modules/assemble/node_modules/template/node_modules/config-cache/index.js:515:28)
    at Assemble.Cache.data (some_project/node_modules/assemble/node_modules/template/node_modules/config-cache/index.js:566:25)
    at Assemble.<anonymous> (some_project/assemblefile.js:25:11)
    at module.exports (some_project/node_modules/assemble/node_modules/orchestrator/lib/runTask.js:34:7)
    at Assemble.Orchestrator._runTask (some_project/node_modules/assemble/node_modules/orchestrator/index.js:273:3)
```

in same time this works well
```
assemble.data({foo: 'bar'});
```

**Comment by hyzhak** [comment]
btw it is reflected in broken tests https://travis-ci.org/assemble/assemble/jobs/65500014

```
  1) assemble data .data() should read files and merge data onto `cache.data`:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/assemble.data.js:28:28)
  2) assemble data .plasma() should read JSON files and return an object.:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/assemble.data.js:65:15)
  3) assemble cache exists(): nested property should exist.:
     AssertionError: expected false to be true
      at Context.<anonymous> (test/cache.js:111:39)
  4) assemble cache exists(): nested property should exist.:
     AssertionError: expected false to be true
      at Context.<anonymous> (test/cache.js:114:41)
  5) assemble data .namespace() should namespace the data using the `:propstring`.:
     AssertionError: expected {} to have property root
      at Context.<anonymous> (test/data.namespace.js:46:36)

```

**Comment by jonschlinkert** [comment]
changed the title to more accurately reflect the issue until we know for sure that it's a bug. (e.g. I use this version, and I don't have the same issue). could you create a gist or past the contents of the yaml file?

**Comment by hyzhak** [comment]
@jonschlinkert sure. here is it https://gist.github.com/hyzhak/3f5ce93ef7ce1cd7b29a. I have used small part wikipedia example http://en.wikipedia.org/wiki/YAML#Sample_document

**Comment by jonschlinkert** [comment]
thanks, that looks like a bug to me. I'll try to confirm here in a bit (unless someone else beats me to it). If so we'll get this fixed asap. thanks!

**Comment by hyzhak** [comment]
@jonschlinkert ok, but what about broken tests, isn't it enough reason to fix bug?

**Comment by jonschlinkert** [comment]
no. not on a branch that has broken tests to begin with lol. Like I said, I'm using this branch and it's not broken for me. I used something almost exactly like what you posted earlier today. Regardless though, as a maintainer I've found that a lot of the time when something is reported as a bug it ends up not being a bug. I just like to verify first so we spend time on the right thing...

**Comment by jonschlinkert** [comment]
closing since data is handled differently in the latest assemble. if this error persists, it's not an assemble issue, it would probably be a js-yaml issue or a gray-matter issue.
