### ISSUE TITLE
Broken when used with Gulp.js

### ISSUE THREAD

**Issue by leehambley** [assemble/assemble#778]
I know that there's assemble/gulp-assemble, and I'm trying to use it, however I get this error message:

```
$ gulp sg
module.js:339
    throw err;
    ^

Error: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/leehambley/Projects/harrow/style-guide/node_modules/assemble/lib/engine.js:10:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

```

Truncated relavant parts of `npm list`:

```
harrow-style-guide@0.0.0 /Users/leehambley/Projects/harrow/style-guide
├─┬ assemble@0.4.42
... snip ...
├─┬ gulp-assemble@0.3.2
... snip ...
```

And finally the relevant parts of my `gulpfile.js`:

```
'use strict';

var assemble     = require('assemble');
var gulpAssemble = require('gulp-assemble');

gulp.task('sg', ['images:copy'], function () {
  gulp
    .src(['*.hbs'])
    .pipe(gulpAssemble(assemble, { layout: 'default' }))
    .pipe(gulp.dest('sg'));
});
```

**Comment by leehambley** [comment]
I see that in spite of Github showing `v0.6.0` as the canonical branch, it's not released to npm yet.

**Comment by jonschlinkert** [comment]
This issue belongs on gulp-assemble. It is in fact released as `assemble@beta`
